### PR TITLE
fix: allow instant reconnects, and always prefer newest connection

### LINKED ISSUE #10: can't re-establish severed gossip connection until the old connection times out
I have some program that panics while connected to gossip.
When i restart it, and get it to connect to one of its old peers it used to be connected to, i see
`ignoring connection: already accepted peer_id=PublicKey(…) origin=Accept.`
Meanwhile, the node attempting to reconnect panics the task with the error: `connection closed: connection lost.`

This appears to happen because Gossip only wants to maintain one connection per pair, and I'd need to wait for the existing (broken) connection to time out.

It would be great to have an option to forcibly replace any existing connection when sending `Command::JoinPeers` from a node.

### PR DESCRIPTION
**Pull request by Frando**
## Description

This should fix #10. It has two changes:

* On `main`, new incoming connections are rejected unless an old incoming connection timed out or are closed properly. This logic was most recently adapted in #22. The current situation is not ideal, because it means that if a peer reconnects without closing the previous connection properly, the new connection will be rejected. This PR changes the logic so that *all* incoming connections are accepted, and we *always* use the newest connection for sending messages. When a new connection is accepted, old connections are not aborted immediately. Instead we close our send stream on the old connection, which makes the peer close its receive stream. If the peer also uses the new connection only, the connection will close on our side as well. This means that multiple connections can coexist, which is maybe not ideal but also not harmful I think. A peer is marked as disconnected for the gossip state machine only when *all* connections to the peer are terminated.

* The hyparview implementation only replied to `Join` messages if the joining peer was not in the receiver's set of active nodes. This means that when a node reconnects, it would not receive a reply unless the receiving node had already detected a timeout on the previous connections and removed the peer from their active nodes. In the case of an ungraceful shutdown, this only happens after the connection times out after 30s with default transport parameters. This PR changes the hyparview implementation to *always* reply to `Join` messages with a `Neighbor` message, also in the case that the joining node is already in the set of active nodes. The same change is applied to receiving `ForwardJoin` . This should have no downsides, as in the regular protocol flow `Join` messages are only sent when first joining nodes. The `Neighbor` reply for nodes that are already active can be a considered a informative renewal of the existing neighbor relation. This fixes the reconnect issue even when connections are not yet timed out.

* Adds a test for this scenario by spawning a gossip node on a single-threaded runtime that can be aborted abrpuply, and then a node with the same node id spawned and connected to the same bootstrap node. The test passes here and fails on main (see #44).

## Change checklist

- [x] Self-review.
- [x] Documentation updates following the [style guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text), if relevant.
- [x] Tests if relevant.
- [x] All breaking changes documented.

### CODE REVIEW

File: src/net.rs [hunk 1]
```diff
@@ -639,10 +639,30 @@ impl Actor {
...
+                    None => {
+                        debug!(peer=%peer_id.fmt_short(), "connection task closed but peer already dropped");
+                    }
+                    Some(PeerState::Pending { .. })=> {
+                        debug!(peer=%peer_id.fmt_short(), "connection task closed but peer in pending state");
+                    }
+                    Some(PeerState::Active { conns, .. }) => {
+                        conns.retain(|x| x.stable_id() != conn.stable_id());
+                        if conns.is_empty() {
+                            debug!(peer=%peer_id.fmt_short(), "all connections closed, notify state of discnnnect");
```
Comment (matheus23) [inline src/net.rs:662]:
```suggestion
                            debug!(peer=%peer_id.fmt_short(), "all connections closed, notify state of disconnect");
```

**Comment by Frando** [comment]
I finally managed to write a test for this. It spawns a gossip instance on a seperate, single-threaded runtime, which we can abort apruptly then, to actually test the "reconnect after ungraceful shutdown" scenario.

This revealed an issue on the proto level: Independent of the connection managment in the `net` module, the hyparview implementation did not reply to joining nodes if they were in the current set of active neighbors. This means that a node that reconnects would not get a reply until the other node had removed it from its set of active nodes, which happens after connection timeout only.

This PR now contains a fix for this: We reply to nodes that send a `Join` even if they are already in the active set.

I am now reasonably confident that this fixes #10.

**Comment by Frando** [comment]
I added some minor refactorings. Only logic change is that the peer is marked disconnected to the proto state machine once the connection we are sending on breaks (because we then cannot send anymore). This will only happen if the other peer goes down, not if it switches to a new connection, because the latter does not close the previous connection as outlined above.

There are now two reports of this fixing the reconnect issues:

* Here https://github.com/n0-computer/iroh-gossip/issues/10#issuecomment-2743962931
* And on Discord where we have a report that this fixes issues when reconnnecting to the same bootstrap nodes after connections broke

So, I'd propose to merge this :)

**Review by matheus23 — APPROVED** [review]
